### ISSUE TITLE
Doctree link dead in readme

### ISSUE THREAD

**Issue by StephenHodgson** [sourcegraph/doctree#7]
Tried to navigate to link in readme for doctree but link was invalid

**Comment by slimsag** [comment]
Thanks for taking a look :) The website isn't up yet, I'm still working on it (we're only like a week into development!)

If you're super eager to try it out, there are some Docker commands you can try here: https://github.com/sourcegraph/doctree#try-it-out-extremely-early-stages

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/doctree/issues/8
